/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiInstantRouteImport } from './routes/api/instant'
import { Route as AdminLearnersRouteImport } from './routes/admin.learners'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin.courses.$courseId'
import { Route as CoursesCourseIdLessonsLessonIdRouteImport } from './routes/courses.$courseId.lessons.$lessonId'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiInstantRoute = ApiInstantRouteImport.update({
  id: '/api/instant',
  path: '/api/instant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLearnersRoute = AdminLearnersRouteImport.update({
  id: '/learners',
  path: '/learners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const CoursesCourseIdLessonsLessonIdRoute =
  CoursesCourseIdLessonsLessonIdRouteImport.update({
    id: '/courses/$courseId/lessons/$lessonId',
    path: '/courses/$courseId/lessons/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/reports': typeof ReportsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/learners': typeof AdminLearnersRoute
  '/api/instant': typeof ApiInstantRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/courses/$courseId/lessons/$lessonId': typeof CoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/reports': typeof ReportsRoute
  '/admin/learners': typeof AdminLearnersRoute
  '/api/instant': typeof ApiInstantRoute
  '/admin': typeof AdminIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/courses/$courseId/lessons/$lessonId': typeof CoursesCourseIdLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/reports': typeof ReportsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/learners': typeof AdminLearnersRoute
  '/api/instant': typeof ApiInstantRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/courses/$courseId/lessons/$lessonId': typeof CoursesCourseIdLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/platform'
    | '/reports'
    | '/admin/courses'
    | '/admin/learners'
    | '/api/instant'
    | '/admin/'
    | '/admin/courses/$courseId'
    | '/admin/courses/'
    | '/courses/$courseId/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/platform'
    | '/reports'
    | '/admin/learners'
    | '/api/instant'
    | '/admin'
    | '/admin/courses/$courseId'
    | '/admin/courses'
    | '/courses/$courseId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/platform'
    | '/reports'
    | '/admin/courses'
    | '/admin/learners'
    | '/api/instant'
    | '/admin/'
    | '/admin/courses/$courseId'
    | '/admin/courses/'
    | '/courses/$courseId/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRoute
  ReportsRoute: typeof ReportsRoute
  ApiInstantRoute: typeof ApiInstantRoute
  CoursesCourseIdLessonsLessonIdRoute: typeof CoursesCourseIdLessonsLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/instant': {
      id: '/api/instant'
      path: '/api/instant'
      fullPath: '/api/instant'
      preLoaderRoute: typeof ApiInstantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/learners': {
      id: '/admin/learners'
      path: '/learners'
      fullPath: '/admin/learners'
      preLoaderRoute: typeof AdminLearnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/courses/$courseId/lessons/$lessonId': {
      id: '/courses/$courseId/lessons/$lessonId'
      path: '/courses/$courseId/lessons/$lessonId'
      fullPath: '/courses/$courseId/lessons/$lessonId'
      preLoaderRoute: typeof CoursesCourseIdLessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCoursesRouteChildren {
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminRouteChildren {
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminLearnersRoute: typeof AdminLearnersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminLearnersRoute: AdminLearnersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRoute,
  ReportsRoute: ReportsRoute,
  ApiInstantRoute: ApiInstantRoute,
  CoursesCourseIdLessonsLessonIdRoute: CoursesCourseIdLessonsLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
